### PR TITLE
adds fields to JobApplication__c

### PR DESCRIPTION
**Pull request by off-nadir-insight**
Adds custom fields to JobApplication__c as requested on AP-23

### CODE REVIEW

**Comment by off-nadir-insight** [comment]
added permission set metadata for new fields

**Review by fritzb100 — COMMENTED** [review]
Great job man, I just have a few comments, lets discuss if you guys don't agree with any of them

Should the salary field have cents? or are we going with no cents?

Can the description field be 131k characters? A job description can be pretty long. I feel that 32k might not be enough sometimes

The Web Link field should be called URL as far as I can tell

Should rating be a picklist field instead of a number? Just because if we needed to update it manually, I wouldn't want to give the user the chance to put 10 in there, I'm ok if you want to go with number, just want to bring up the point for discussion

Can the notes field be max 131k?

**Comment by off-nadir-insight** [comment]
- Salary -> Currency(16, 2) 
- Description -> Long Text Area(131072)
- Web link -> renamed to `Url`
- Rating - I wasn't sure if we used picklists, if we'd still be able to numerically sort by ranking. Albeit, using numbers would require us to build in validation rules to ensure integers larger than 5 weren't selected. (In LWC would number usage make a slider element available?)
- - updated to picklist [5, 4, 3, 2, 1]
- Notes -> Long Text Area(131072)

**Review by fritzb100 — APPROVED** [review]

**Comment by fritzb100** [comment]
Approve, Nice

**Pull request merged**
